DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id int(12) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    email VARCHAR(75) NOT NULL UNIQUE,
    phone_number VARCHAR(75) NOT NULL,
    username VARCHAR(75) NOT NULL UNIQUE,
    password_salt VARCHAR(128) DEFAULT NULL,
    password_hash VARCHAR(256) DEFAULT NULL,
    isEmployee BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK(LENGTH(password) >= 8)
);