DROP TABLE IF EXISTS queue;
DROP TABLE IF EXISTS temp_users;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS stores;

CREATE TABLE stores(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE users (
    id int(12) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    email VARCHAR(75) NOT NULL UNIQUE,
    phone_number VARCHAR(75) NOT NULL,
    username VARCHAR(75) NOT NULL UNIQUE,
    password_salt VARCHAR(128) DEFAULT NULL,
    password_hash VARCHAR(256) DEFAULT NULL,
    is_employee BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE temp_users (
    id integer PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE queue(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    store_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL UNIQUE,
--    temp_user_id INTEGER,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--    FOREIGN KEY (temp_user_id) REFERENCES temp_users(id) ON DELETE CASCADE
);
